apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beszel-hub
  namespace: beszel
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - beszel.lab.paroparo.it
      # Traefik usa il wildcard di default (wildcard-lab-paroparo-it-tls da kube-system)
  rules:
    - host: beszel.lab.paroparo.it
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: beszel-hub
                port:
                  number: 8090
