apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:jTpP5/3pJ6yNkt7xSjvNZtGQg3jWT62+kRvdjg+kNDgJvoLM3xxrvhj+5rmsJM9jWB1+x94=,iv:MnNPBUsK3RZTjpzyhtyM9S0c8RQRupJgWMWCynhP35s=,tag:7Z4H44JKvR0unupqI26+DQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkN1kwL0tYU0lWU09ubkpk
            OGN3aHdNdjYwY2ZpelhXQmpYbzdrcnZSV3hjCkIyWEpwY3RQd1FNTmVRK0tmM1J2
            QS9pUWJqRGdmTE43Nmk0WFpNN3VnTjgKLS0tIFpWdWdVS3AwaDNiZUtwc0dTQXhD
            clJxZ3BXeEZ5c1FtQkRhTk10aHQrdFUKy4rHX8/xiP/+r167iY+lF2LbgUWKiJPy
            q/dDxBC97TSyZQAqo9u3AB3RmWChpap5kmBUWYb9VdB7+PiSkhDdvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xha4vvyd2593c9cx2qnnzsfw7l5enj2yncvk3d9j62gsp0ql6y0qzmt6g5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-18T16:51:30Z"
    mac: ENC[AES256_GCM,data:utaKUKA3mF8wnioOaJI6rPyg0AZXOg9nITGsIISUjQpi9C0eA9T47+jfm6XsrWKGfV2wy3emerjujFUh3AIvrYa+kiH6Qa6HureLMr5YsxP1o/VJvL5yPvfZ7ffsdsp72KxBNmyWg5bSGbUBGea0o+iCjOXmzqNj2QAI5dGfPqU=,iv:EItZE4h4ATgppEgGbCMDjI2a2oNBAozoXtEsUsJuOUg=,tag:SvU0OHMDqiW48/9oI6XLBg==,type:str]
    version: 3.13.1
