apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    title: Astra Homelab
    headerStyle: clean
    theme: dark
    color: slate
    layout:
      Infrastructure:
        style: row
        columns: 4

  services.yaml: |
    - Infrastructure:
        - Technitium:
            href: https://10.0.40.2:5380
            description: DNS server (nebula)
            icon: technitium.png
        - Flux:
            href: https://github.com/iltruma/nebula-nix
            description: GitOps repo
            icon: flux-cd.png
        - Beszel:
            href: https://beszel.lab.paroparo.it
            description: Monitoring
            icon: beszel.png

  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank

  bookmarks.yaml: |
    - Repos:
        - Nebula-nix:
            - abbr: NB
              href: https://github.com/iltruma/nebula-nix
