apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - jellyfin.lab.paroparo.it
      # Traefik usa il wildcard di default (wildcard-lab-paroparo-it-tls da kube-system)
  rules:
    - host: jellyfin.lab.paroparo.it
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin
                port:
                  number: 8096